### ISSUE TITLE
Architecture for the long haul

### ISSUE THREAD

**Issue by scottkellum** [SassConf/sassconf.github.io#4]
I’m not really feelin’ Harp on this project. Maybe I’m just being old and having trouble adjusting.
- We need something solid that we don’t have to re-invent every year.
- Something we are familiar with and something that is easy for new contributors.
- Easy build/deploy process.
- Ideally something that already has roots in the Sass community.

IMO Middleman is a clear winner. It’s not really new or shiny but for a project who's goal is longevity that is a good thing. Node is a shiny new thing but I don’t see many advantages for our use case. We aren’t doing any frontend/backend communication as this is a static site so the key advantage to Node making this communication easy isn’t a factor.

Not sure how we settled on Harp or discussions that went into it. I have some reservations about it but maybe the pros/cons have been weighted already.

@misscs @elyseholladay

**Comment by jina** [comment]
+1 middleman

—

**Comment by elyseholladay** [comment]
:white_check_mark:
