### ISSUE TITLE
Missing info

### ISSUE THREAD

**Issue by TheJaredWilcurt** [SassConf/sassconf.github.io#5]
I'd put some more emphasis on the date and location of the conference. And either pricing, or a date of when pricing will be decided. A link to buy tickets, or a date of when you'll be able to. There are several places I've seen mention signing up for a newsletter which is ew, but whatever, if that's the only way, sure. Except there's no link to do so.

**Comment by elyseholladay** [comment]
@TheJaredWilcurt We were waiting to finalize venue and date, and were a belated on updating the site after the CFP closed. You're right, it's important info! Site is all new and shiny now, and tickets are on sale! (As for the newsletter, it's the best way we can email everyone about tickets and what not, so a necessary evil! Not everyone is on Twitter :smile: )
