### ISSUE TITLE
On small viewports, the "email about sponsorship button" unintentionally deviates from the consistency of other buttons on this year's site for SassConf (2015) 

### ISSUE THREAD

**Issue by lozandier** [SassConf/sassconf.github.io#9]
As shown by the following screenshot below, the "email about subscription button" deviates from the visual consistency wonderfully crafted for this year's SassConf:

<img width="1440" alt="screen shot 2015-07-17 at 10 28 45 pm" src="https://cloud.githubusercontent.com/assets/1223224/8759993/c3cc7716-2cd3-11e5-894c-29b9d0f381d3.png">

WIth the font size being calculated w/ calc, changing the base `em` value to approximately `.8em` fixed the problem: 

<img width="1440" alt="screen shot 2015-07-17 at 10 30 20 pm" src="https://cloud.githubusercontent.com/assets/1223224/8760000/f670890a-2cd3-11e5-854a-20db97d9b06e.png">

Recalling this property declaration may be initialized and maintained by a mixin of a technique I don't yet have a strong grasp of, I decided it made the most sense to file this as an issue instead of filing a pull request. 

If I'm mistaken, a media query around the size of an iPhone 4 (~`325px` that is converted to `ems`) that utilizes `.8em` seems like a quick solution.

**Note: Also tested on Browserstack; a register button  after the diversity funding pricing also has the same problem**

**Comment by elyseholladay** [comment]
thanks @lozandier! I just had all the button type the same and that one was longer than the others (last minute addition.) easy to fix either by changing button type size at small breakpoints, or forcing long-text buttons to wrap/center. I can address this, or if you want to take it on:
1. branch off `source` branch
2. edit type size in `buttons.scss`; you can use the `@include media(grid-NN) {}` mixin, where NN is `sm` `med` `lg` `xl` (see `breakpoints.scss`.) The breakpoints scale up, so 0-300 is default (outside of a MQ it will apply), 300-600 I think is `sm` and anything at `sm` applies all the way on up unless overridden. so you can change default button text size and then at `med` make it larger.
3. submit a PR

:sparkling_heart:

**Comment by lozandier** [comment]
@elyseholladay No problem, I didn't see the source Sass files today or yesterday unless I'm looking in the wrong place (& Github is as well)? I assumed Sass was used to compile the stylesheets inside `stylesheets`

**Comment by elyseholladay** [comment]
@lozandier Yes, if you check out the `source` branch, they're in `source/stylesheets`: https://github.com/SassConf/sassconf.github.io/tree/source/source/stylesheets

When you make your branch, run `bundle install` and then run `middleman server`; it will compile the Sass files as well as livereload for you.

Everything in `master` branch is static compiled HTML/inlined CSS.

**Comment by lozandier** [comment]
Doh, thanks for reinforcing the critical message in bold about this I
somehow missed.
On Saturday, July 18, 2015, elyse holladay notifications@github.com wrote:

> @lozandier https://github.com/lozandier Yes, if you check out the source
> branch, they're in source/stylesheets:
> https://github.com/SassConf/sassconf.github.io/tree/source/source/stylesheets
> 
> When you make your branch, run bundle install and then run middleman
> server; it will compile the Sass files as well as livereload for you.
> 
> Everything in master branch is static compiled HTML/inlined CSS.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SassConf/sassconf.github.io/issues/9#issuecomment-122597879
> .

## 

Kevin Lozandier
lozandier@gmail.com lozandier@gmail.com

**Comment by elyseholladay** [comment]
@lozandier haha it's all good, using other people's code/steps for the first time is weird.

**Comment by lozandier** [comment]
@elyseholladay  Yeah, I couldn't figure it out how to quantify the `ms-respond` mixin to change its scale to get an output ~`.8em` for viewports  that don't support viewport units & ~`4vw` for browsers that do. 

It generates the media queries itself, so it's tricker than I thought; with mqs I called with the mixins you mentioned not working unless I didn't account for a caching mechanism foreign to me. 

From the previous knowledge I had with it I'm trying to remember deep in my long-term memory reserves this evening, it was settable via  `$ms-range`, but couldn't find that with hub superpowered `git grep`. 

Also, `config.output_style = :compressed`  on line 7 of `config.rb` is problematic when debugging Sass in this repo; I don't know if Middleman supports these environment switches, but the following seemingly would be dev friendly for those who prefer debugging in the browser/rapid prototyping (I couldn't get Compass's `sourcemap` to work or where `sass's is being configured though (I've gotten too familiar with gulps & CLI way of doing that it seems):

``` ruby
if environment == :development 
  config.output_style = :expanded
else
   config.output_style = :compressed
end
```

**Edit: It seems it _does_, I got the expected output locally, will push that change in a moment in ~~to a new~~ my existing pull request**

**Comment by scottkellum** [comment]
:wave: @lozandier thanks for opening this. Lets start with the easy stuff, yeah I can change the output style like that, will submit a PR in a few. I’ve never really felt the need to use source maps with Sass so never dug into how to set them up.

As far as our browser compatibility table goes, I think vw and calc() for the text is ok. I’m not very concerned by this, especially because if things fail the size should drop to the previous media query

`$ms-range` is here: https://github.com/SassConf/sassconf.github.io/blob/source/source/stylesheets/_settings.scss#L41-L42

For that specific instance, because you want it to be smaller than the text instead of larger, I might go with a specific value of .8em. Using the ms respond mixin for this would mean the size would get smaller, not larger, as the site gets bigger.

**Comment by elyseholladay** [comment]
@lozandier just FYI, this should be fixed now :)
